Turner.Titles.Web/Controllers/TitleController.cs
using System.Web;
using System.Web.Mvc;
using Turner.Titles.Service;

namespace Turner.Titles.Web.Controllers
{
    public class TitleController : Controller
    {
        private readonly ITitleService _titleService;
        public TitleController()
        {
            _titleService = new TitleService();
        }

        // GET: Title
        public ActionResult List()
        {
            
            return View();
        }

        [HttpGet]
        public JsonResult Search(string query)
        {
            var titles = _titleService.SearchTitleByName(Server.UrlDecode(query));
            return Json(titles, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Details(int? id)
        {
            if(!id.HasValue)
                return RedirectToAction("List");

            var title = _titleService.GetTitleById(id.Value);
            if (title == null)
                return RedirectToAction("List");

            return View(title);
        }

        public ActionResult NotFound()
        {
            return View();
        }
        
    }
}

Turner.Titles.Web/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "NotFound";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <h2>404 - Not Found</h2>
    <h3>Sorry the page you are looking for is not found</h3>
</div>

Turner.Titles.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Turner Movies</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Turner Movies", "List", "Title", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Turner</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/uielement")
    @RenderSection("scripts", required: false)
</body>
</html>